title: Git Templates
email: sylvan.ledeunff@gmail.com
description: Showcase website to document all my "git templates".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://templates.sylvan.ovh" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: theme
palette:
  primary:
    color: blue
    shade: darken-1
  ternary:
    color: pink
    shade: darken-3
  secondary:
    color: teal
    shade: accent-3

collections:
  templates:
    output: true

plugins:
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true

menu_entries:
  - title: "Browse templates"
    link: "/"
  - title: "About"
    link: "/about"

toc:
  list_class: sidenav-close
  sublist_class: browser-default
  min_level: 1
  max_level: 4

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
