title: Git Templates
email: sylvan.ledeunff@gmail.com
description: Showcase website to document all my "git templates".
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://templates.sylvan.ovh" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: theme
palette:
  primary:
    color: blue
    shade: darken-1
  ternary:
    color: pink
    shade: darken-3
  secondary:
    color: teal
    shade: accent-3

collections:
  templates:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'
